---
version: '3'

services:
  proxy:
    image: "docker-registry/proxy"
    build:
      context: ./
      dockerfile: Dockerfile.proxy
    ports:
      - 443:443
      - 80:80
    links:
      - registry:registry

  registry:
    restart: always
    image: "docker-registry/registry"
    build:
      context: ./
      dockerfile: Dockerfile.registry
      args:
        username: username
        password: password
    ports:
      - 5000:5000
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_STORAGE=oss
      - REGISTRY_STORAGE_OSS_ACCESSKEYID=<access-key-id>>
      - REGISTRY_STORAGE_OSS_ACCESSKEYSECRET=<access-key-secret>
      - REGISTRY_STORAGE_OSS_REGION=<region>
      - REGISTRY_STORAGE_OSS_BUCKET=<bucket>
      - REGISTRY_STORAGE_OSS_ENDPOINT=<bucket>.<region>.aliyuncs.com
